### ISSUE TITLE
Proposed T cell hierarchy

### ISSUE THREAD

**Issue by nicolevasilevsky** [obophenotype/human-phenotype-ontology#2461]
Per our conversation today on the phenotype editors call, we will prioritize creating a new hierarchy under HP_0002843 Abnormality of T cells

Current hierarchy:
(please add new term requests under existing terms as **NTR: term** (and use **bold** format)

- [x] HP_0002843 Abnormality of T cells
- [x] - HP_0030332 Abnormal T cell morphology
- [x] -- HP_0030333 Abnormal alpha-beta T cell morphology
- [x] --- HP_0030334 Abnormal CD4-positive, CD25-positive, alpha-beta regulatory T cell morphology
- [x] ---- HP_0030335 Abnormal CD4-positive, CD25-positive, alpha-beta regulatory T cell count
- [x] ----- HP_0030336 Absence of CD4-positive, CD25-positive regulatory T cells
- [x] ----- HP_0030337 Elevated CD4-positive, CD25-positive regulatory T cell count
- [x] -- HP_0011839 'Abnormality of T cell count'
- [x] --- HP_0025540 Abnormal T cell subset distribution
- [x] **Suggest renaming to 'Abnormal proportion of T cells'**
- [x] ---- **NTR: Abnormal naive T cell proportion** #2420
- [x] ----- **NTR: Reduced proportion of naive T cells** #2420 
- [x] ---- **NTR: Abnormal proportion of CD4 T cells** #2436
- [x] ---- **NTR: Abnormal proportion of CD8 T cells** #2436
- [x] -- HP_0100828 Increase in T cell count
- [x] --- **NTR:  Abnormal proportion of CD4-negative/CD8-negative, alpha-beta T cells'**
- [x] --- HP_0002851 Increased number of 'CD4-/CD8- T cells expressing alpha/beta T-cell receptors **suggest revising label to 'Increased proportion of CD4-negative/CD8-negative, alpha-beta T cells'** *This should be a child of the new termAbnormal proportion of CD4-negative/CD8-negative, alpha-beta T cells'*
- [x] ---- **NTR: Abnormal CD4-negative/CD8-negative, alpha-beta regulatory T cell distribution** #2396 
- [x] --- HP_0002845 Increased number of peripheral CD3+ T cells
- [x] **suggest revising label to 'Increased proportion of CD3+ T cells'**
- [x] -- HP_0002853 Increased proportion of HLA DR+ and CD57+ T cells
- [x] - HP_0011840 Abnormality of T cell physiology
- [x] -- **NTR: Abnormal T cell proliferation** #2444
- [x] --- **NTR: Impaired antigen-specific T-cell proliferation** #2447 
- [x] -- HP_0002963 Abnormal delayed hypersensitivity skin test
- [x] --- HP_0002965 Cutaneous anergy
- [x] --- HP_0002972 Reduced delayed hypersensitivity
- [x] -- HP_0410035 Abnormal T cell activation
- [x] --- **NTR: Deficient CD40 expression** #2443 
- [x] --- **NTR: Abnormal CD69 upregulation upon TCR activation** #2452 
- [x] ----**NTR: Decreased CD69 upregulation upon TCR activation** #2452 
- [x] --- **NTR: Abnormal CD25 upregulation upon TCR activation** #2451 
- [x] ---- **NTR: Decreased CD25 upregulation upon TCR activation** #2451 
- [x] --- HP_0005419 Decreased T cell activation
- [x] -- HP_0005354 Absent cellular immunity
- [x] -- HP_0005397 Exaggerated cellular immune processes
- [x] -- HP_0005435 Impaired T cell function
- [x] --- **NTR: Increased exhaustion markers on T cells** #2416 
- [x] --- HP_0030253 Defective T cell proliferation
- [x] --- HP_0005409 Markedly reduced T cell function
- [x] -- HP_0005402 Primary T-lymphocyte immune abnormalities

**Comment by pnrobinson** [comment]
We will need to consider carefully how to structure the hierarchy. Clinically, the following four T cell subsets are commonly encountered: naive, central memory, effector memory, and terminally differentiated effector memory cells re-expressing CD45RA (TEMRA). An analogous subhierarchy exists for CD4+ and CD8+ T cells. Different markers have been used at different times over the last decades, and we need to try to make our definition reflect current practice and to add old marker combinations as exact or related synonyms.
 
The following comes from http://onlinelibrary.wiley.com/doi/10.1002/cyto.a.22351/full

The surface markers typically used to define the four main sub-populations of T cells can be summarized as follows; N (CCR7+, CD27++, CD28++, CD45RA+), CM (CCR7+, CD27+++, CD28+++, CD45RA−), EM (CCR7−, CD27+/−, CD28+/−, CD45RA−) and TEMRA (CCR7−, CD27−, CD28−, CD45RA+)

**Comment by cmungall** [comment]
Sorry mr broken record here...

I suggest you don't think about the hierarchy at all, just define using CL and let the reasoner do the work.

**Comment by pnrobinson** [comment]
@nicolevasilevsky This label (Abnormal proportion of T cells) seems ambiguous because it does not say whether the proportion is say B cell vs T cell or whether the proportion refers to T cell subsets (which is what we want). I agree that the current label (Abnormal T cell subset distribution) is not easily grokk-able. Can we continue to brainstorm about what the optimal label should be though?

**Comment by pnrobinson** [comment]
@cmungall @drseb  I currently would be a bigger fan of letting the reasoner check our work and would like to see us make Seb's Q/C tool a part of the pipeline again. The raw CL hierarchy has lots of cells that are not really used in clinical workups and I think we need to do the first pass manually.

**Comment by mellybelly** [comment]
we should be able to add a subset tag in CL to help this

**Comment by cmungall** [comment]
not sure a subset tag is necessary, it's not different from any other ontology. You simply use the cell types that you care about, the reasoner will still infer the correct results. The terms could be added in protege or incaform

**Comment by pnrobinson** [comment]
Absent cellular immunity is being used to annotate only one disease, https://omim.org/entry/267500
It is referring to lack of T cell function. I am going to change the primary label.

**Comment by pnrobinson** [comment]
The term Exaggerated cellular immune processes is inexact. It is being used to annotate one disease in our corpus.  I am leaving it for now but it would be good to be more precise as to what is being observed. It may be that it was a positive Kveim test, but this test is no longer frequently used.

**Comment by pnrobinson** [comment]
All of these terms have been processed, I am closing the issue.
