### ISSUE TITLE
Epic: Finalise HP QC pipeline and integrate all _general_ tests in standard ODK setup

### ISSUE THREAD

**Issue by matentzn** [obophenotype/human-phenotype-ontology#4974]
We started making [a list of all the QC](https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/QC.md) that is being run for HP, and present it at the next Ontology Huddle.

Other open issues:
- [ ] [QC for permitted and required annotations on HP classes](https://github.com/obophenotype/human-phenotype-ontology/issues/4885)
- [ ] [Standardise ORCID formatting](https://github.com/obophenotype/human-phenotype-ontology/issues/4966)
- [ ] [Tidy up xrefs](https://github.com/obophenotype/human-phenotype-ontology/issues/4923)

**Comment by matentzn** [comment]
https://github.com/obophenotype/human-phenotype-ontology/blob/master/src/ontology/QC.md

**Comment by drseb** [comment]
This ticket is mixing the documentation task with actual formatting tasks. I would prefer to split these up.

**Comment by matentzn** [comment]
Yeah you are right; I was not not sure how to split; I guess my intention for the ticket was to have a single discussion threat that looks at the current QC, decides what else is needed and then extract the bits that should be elevated to all Monarch ontologies.. What would be a good way to split/name the issue in your opinion?

**Comment by drseb** [comment]
Ah okay, I see. Maybe rename the ticket. Not sure it is really a ticket. When will it be closed? 
There are already two tickets for the TO-DO's and the QC seems properly documented.

**Comment by matentzn** [comment]
Haha yeah good point. It will be closed when all other QC related tickets are dealt with and the tests are integrated in the ODK for the benefit of all other (Monarch) ontologies :P So in my opion, first step would be to document, second step to review (what else do we need, what checks are really redundant and irrelevant), third step would be to implement all checks that HP does bit no one else as part of the ODK so that other ontologies can profit from it.

Note that tickets with capturing multiple tickets can be understood as `Epics` (check [here for the corresponding Monarch ontology epic](https://github.com/monarch-initiative/monarch-ontology/issues/11)). These are container tickets addressing a complex, but coherent issue like `Standardising the QC pipeline` and reference all the individual tickets that need to be addressed in order to complete it.

**Comment by pnrobinson** [comment]
@matentzn Is this closeable?

**Comment by matentzn** [comment]
Its not done; If I have not acted on it by the 31st May you can close it. If you just want it gone, I can move it to another repo, no problem.

**Comment by pnrobinson** [comment]
@matentzn  I will close this, since there are no clear action items but feel free to make new issues for current tasks if any!
